### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by syf0215** [Chen-Yang-Liu/PromptCC#3]
作者您好，我在推理和训练时都遇到了这个问题：
`File "/PromptCC/models_CC.py", line 264, in forward
    clip_emb_A, img_feat_A = self.clip_model.encode_image(img_A)
ValueError: too many values to unpack (expected 2, got 1)`
看起来是因为原始的CLIP输出的是一整张图的特征，而这里的img_feat_A似乎是(N, h*w, 512)的特征
请问您可以分享下是怎么修改CLIP让它输出patch-level的图像特征吗？
感谢!

**Comment by Chen-Yang-Liu** [comment]
> 作者您好，我在推理和训练时都遇到了这个问题： `File "/PromptCC/models_CC.py", line 264, in forward clip_emb_A, img_feat_A = self.clip_model.encode_image(img_A) ValueError: too many values to unpack (expected 2, got 1)` 看起来是因为原始的CLIP输出的是一整张图的特征，而这里的img_feat_A似乎是(N, h*w, 512)的特征 请问您可以分享下是怎么修改CLIP让它输出patch-level的图像特征吗？ 感谢!

很抱歉那是由于我们修改了CLIP package的源码，你可以在CLIP.model.VisionTransformer中修改VisionTransformer的forward如下来解决那个bug：
<img width="884" alt="1" src="https://github.com/Chen-Yang-Liu/PromptCC/assets/77491712/6e4b5723-dabf-4dab-8fa2-acce80674adb">

**Comment by alicankrc2** [comment]
Hi, I receive the same error in different line: 

Traceback (most recent call last):
  File "D:\PromptCC\train.py", line 254, in <module>
    main(args)
  File "D:\PromptCC\train.py", line 189, in main
    epoch=epoch)
  File "D:\PromptCC\train.py", line 55, in train
    Sim_cls_AB, pre_flag, outputs = Caption_model(caps, changeflag, ori_img, mask)
  File "C:\Users\AliCanKaraca\.conda\envs\RSICCformer\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PromptCC\models_CC.py", line 292, in forward
    Sim_cls_AB, pre_flag, prefix_projections = self.Image_Encoder(changeflag, ori_img) #.view(-1, self.prefix_length, self.gpt_embedding_size)
  File "C:\Users\AliCanKaraca\.conda\envs\RSICCformer\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PromptCC\models_CC.py", line 191, in forward
    clip_emb_A, img_feat_A = self.clip_model.encode_image(img_A)
ValueError: too many values to unpack (expected 2)

**Comment by jimmywang1230** [comment]
作者您好，我在查看您的代码AttentiveEncoder中SD-SSM与TT-SSM时，发现与您论文提出的架构有显著的差异，想询问您要以哪边的为主呢?

**Comment by Chen-Yang-Liu** [comment]
> 作者您好，我在查看您的代码AttentiveEncoder中SD-SSM与TT-SSM时，发现与您论文提出的架构有显著的差异，想询问您要以哪边的为主呢?

您好，事实上，论文中的结构图和代码中的模块结构是等价的~

**Comment by XingCando** [comment]
作者您好！请问CLIP package的源码在哪呢？是需要自己去对应的CLIP论文里下载吗，因为我没看见你的工作目录有。

**Comment by Chen-Yang-Liu** [comment]
> 作者您好！请问CLIP package的源码在哪呢？是需要自己去对应的CLIP论文里下载吗，因为我没看见你的工作目录有。

在安装的conda环境下有对应的clip包

**Comment by XingCando** [comment]
> > 作者您好！请问CLIP package的源码在哪呢？是需要自己去对应的CLIP论文里下载吗，因为我没看见你的工作目录有。
> 
> 在安装的conda环境下有对应的clip包



> > 作者您好！请问CLIP package的源码在哪呢？是需要自己去对应的CLIP论文里下载吗，因为我没看见你的工作目录有。
> 
> 在安装的conda环境下有对应的clip包

已解决，谢谢作者

**Comment by jimmywang1230** [comment]
作者您好想请问您是否可以提供，论文中特征热力图生成的代码，我自己撰写出来的结果与您的差异甚大，谢谢
