### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by X-Wang-99** [Chen-Yang-Liu/PromptCC#4]
作者，你好。
我在复现你的网络，train.py跑到1000iter进行验证的时候出现这个问题。
Traceback (most recent call last):
  File "F:/0-code/image-description/Chg2Cap-main/test.py", line 220, in <module>
    main(args)
  File "F:/0-code/image-description/Chg2Cap-main/test.py", line 139, in main
    nochange_metric = get_eval_score(nochange_references, nochange_hypotheses)
  File "F:\0-code\image-description\Chg2Cap-main\utils.py", line 75, in get_eval_score
    score_i, scores_i = scorer.compute_score(ref, hypo)
  File "F:\0-code\image-description\Chg2Cap-main\eval_func\meteor\meteor.py", line 41, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "F:\0-code\image-description\Chg2Cap-main\eval_func\meteor\meteor.py", line 65, in _stat
    self.meteor_p.stdin.write(score_line + '\n')
OSError: [Errno 22] Invalid argument
请问一下你遇到过此类问题嘛？应该如何修改。
感谢。

**Comment by Chen-Yang-Liu** [comment]
> 作者，你好。 我在复现你的网络，train.py跑到1000iter进行验证的时候出现这个问题。 Traceback (most recent call last): File "F:/0-code/image-description/Chg2Cap-main/test.py", line 220, in main(args) File "F:/0-code/image-description/Chg2Cap-main/test.py", line 139, in main nochange_metric = get_eval_score(nochange_references, nochange_hypotheses) File "F:\0-code\image-description\Chg2Cap-main\utils.py", line 75, in get_eval_score score_i, scores_i = scorer.compute_score(ref, hypo) File "F:\0-code\image-description\Chg2Cap-main\eval_func\meteor\meteor.py", line 41, in compute_score stat = self._stat(res[i][0], gts[i]) File "F:\0-code\image-description\Chg2Cap-main\eval_func\meteor\meteor.py", line 65, in _stat self.meteor_p.stdin.write(score_line + '\n') OSError: [Errno 22] Invalid argument 请问一下你遇到过此类问题嘛？应该如何修改。 感谢。

我建议先尝试使用本仓库提供的eval_func下的所有文件而不是Chg2Cap-main所提供的，然后观察是否还有问题

**Comment by X-Wang-99** [comment]
不好意思，由于在复现你的代码和Chg2Cap的代码时，都出现了相同的问题。我刚才重新训练了一次。在你的代码中也出现了这个问题，所以想请教一下有什么建议修改嘛？
12-30  20 : 58 : 01
Epoch:0/40 step:0/1065 Loss:4.5288 AVG_Loss:4.5288 CAP_Loss:13.5864 CAP_AVG_Loss:13.5864 Flag_Loss:0.0854 Flag_AVG_Loss:0.0000 CAP_Acc:0.00 Flag_Acc:96.88 Batch_time:62.84s
Epoch:0/40 step:100/1065 Loss:2.8660 AVG_Loss:3.5240 CAP_Loss:8.5979 CAP_AVG_Loss:10.5721 Flag_Loss:0.1151 Flag_AVG_Loss:0.0000 CAP_Acc:1.62 Flag_Acc:93.97 Batch_time:0.46s
Epoch:0/40 step:200/1065 Loss:1.4434 AVG_Loss:2.7639 CAP_Loss:4.3301 CAP_AVG_Loss:8.2916 Flag_Loss:0.0785 Flag_AVG_Loss:0.0000 CAP_Acc:4.06 Flag_Acc:94.15 Batch_time:0.49s
Epoch:0/40 step:300/1065 Loss:1.4151 AVG_Loss:2.3168 CAP_Loss:4.2452 CAP_AVG_Loss:6.9505 Flag_Loss:0.0853 Flag_AVG_Loss:0.0000 CAP_Acc:4.50 Flag_Acc:94.14 Batch_time:0.47s
Epoch:0/40 step:400/1065 Loss:1.3260 AVG_Loss:2.0797 CAP_Loss:3.9781 CAP_AVG_Loss:6.2391 Flag_Loss:0.1448 Flag_AVG_Loss:0.0000 CAP_Acc:5.75 Flag_Acc:94.19 Batch_time:0.47s
Epoch:0/40 step:500/1065 Loss:1.2548 AVG_Loss:1.9195 CAP_Loss:3.7643 CAP_AVG_Loss:5.7585 Flag_Loss:0.1571 Flag_AVG_Loss:0.0000 CAP_Acc:7.88 Flag_Acc:94.17 Batch_time:0.48s
Epoch:0/40 step:600/1065 Loss:1.2688 AVG_Loss:1.8003 CAP_Loss:3.8065 CAP_AVG_Loss:5.4010 Flag_Loss:0.0826 Flag_AVG_Loss:0.0000 CAP_Acc:7.00 Flag_Acc:94.20 Batch_time:0.47s
Epoch:0/40 step:700/1065 Loss:0.9654 AVG_Loss:1.7030 CAP_Loss:2.8961 CAP_AVG_Loss:5.1090 Flag_Loss:0.0893 Flag_AVG_Loss:0.0000 CAP_Acc:9.06 Flag_Acc:94.21 Batch_time:0.47s
Epoch:0/40 step:800/1065 Loss:0.8386 AVG_Loss:1.6129 CAP_Loss:2.5157 CAP_AVG_Loss:4.8387 Flag_Loss:0.1902 Flag_AVG_Loss:0.0000 CAP_Acc:12.38 Flag_Acc:94.25 Batch_time:0.48s
Epoch:0/40 step:900/1065 Loss:0.7938 AVG_Loss:1.5327 CAP_Loss:2.3815 CAP_AVG_Loss:4.5980 Flag_Loss:0.2151 Flag_AVG_Loss:0.0000 CAP_Acc:12.44 Flag_Acc:94.28 Batch_time:0.47s
Epoch:0/40 step:1000/1065 Loss:0.7327 AVG_Loss:1.4602 CAP_Loss:2.1982 CAP_AVG_Loss:4.3807 Flag_Loss:0.0488 Flag_AVG_Loss:0.0000 CAP_Acc:12.56 Flag_Acc:94.26 Batch_time:0.46s
12-30  21 : 07 : 35
using real changeflag
 EVALUATING AT BEAM SIZE 3: 100%|██████████| 6665/6665 [06:13<00:00, 17.85it/s]
len(nochange_references): 666
len(change_references): 667
['Bleu_1', 'Bleu_2', 'Bleu_3', 'Bleu_4'] [0.9999999999992492, 0.9999999999991867, 0.9999999999990823, 0.9999999999988425]
Traceback (most recent call last):
  File "F:/0-code/image-description/PromptCC-main/train.py", line 254, in <module>
    main(args)
  File "F:/0-code/image-description/PromptCC-main/train.py", line 196, in main
    metrics = evaluate(args, test_loader, tokenizer, Caption_model)
  File "F:\0-code\image-description\PromptCC-main\eval2.py", line 194, in evaluate
    metrics = get_eval_score(nochange_references, nochange_hypotheses)
  File "F:\0-code\image-description\PromptCC-main\utils.py", line 188, in get_eval_score
    score_i, scores_i = scorer.compute_score(ref, hypo)
  File "F:\0-code\image-description\PromptCC-main\eval_func\meteor\meteor.py", line 41, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "F:\0-code\image-description\PromptCC-main\eval_func\meteor\meteor.py", line 65, in _stat
    self.meteor_p.stdin.write(score_line + '\n')
OSError: [Errno 22] Invalid argument

**Comment by Chen-Yang-Liu** [comment]
> 不好意思，由于在复现你的代码和Chg2Cap的代码时，都出现了相同的问题。我刚才重新训练了一次。在你的代码中也出现了这个问题，所以想请教一下有什么建议修改嘛？ 12-30 20 : 58 : 01 Epoch:0/40 step:0/1065 Loss:4.5288 AVG_Loss:4.5288 CAP_Loss:13.5864 CAP_AVG_Loss:13.5864 Flag_Loss:0.0854 Flag_AVG_Loss:0.0000 CAP_Acc:0.00 Flag_Acc:96.88 Batch_time:62.84s Epoch:0/40 step:100/1065 Loss:2.8660 AVG_Loss:3.5240 CAP_Loss:8.5979 CAP_AVG_Loss:10.5721 Flag_Loss:0.1151 Flag_AVG_Loss:0.0000 CAP_Acc:1.62 Flag_Acc:93.97 Batch_time:0.46s Epoch:0/40 step:200/1065 Loss:1.4434 AVG_Loss:2.7639 CAP_Loss:4.3301 CAP_AVG_Loss:8.2916 Flag_Loss:0.0785 Flag_AVG_Loss:0.0000 CAP_Acc:4.06 Flag_Acc:94.15 Batch_time:0.49s Epoch:0/40 step:300/1065 Loss:1.4151 AVG_Loss:2.3168 CAP_Loss:4.2452 CAP_AVG_Loss:6.9505 Flag_Loss:0.0853 Flag_AVG_Loss:0.0000 CAP_Acc:4.50 Flag_Acc:94.14 Batch_time:0.47s Epoch:0/40 step:400/1065 Loss:1.3260 AVG_Loss:2.0797 CAP_Loss:3.9781 CAP_AVG_Loss:6.2391 Flag_Loss:0.1448 Flag_AVG_Loss:0.0000 CAP_Acc:5.75 Flag_Acc:94.19 Batch_time:0.47s Epoch:0/40 step:500/1065 Loss:1.2548 AVG_Loss:1.9195 CAP_Loss:3.7643 CAP_AVG_Loss:5.7585 Flag_Loss:0.1571 Flag_AVG_Loss:0.0000 CAP_Acc:7.88 Flag_Acc:94.17 Batch_time:0.48s Epoch:0/40 step:600/1065 Loss:1.2688 AVG_Loss:1.8003 CAP_Loss:3.8065 CAP_AVG_Loss:5.4010 Flag_Loss:0.0826 Flag_AVG_Loss:0.0000 CAP_Acc:7.00 Flag_Acc:94.20 Batch_time:0.47s Epoch:0/40 step:700/1065 Loss:0.9654 AVG_Loss:1.7030 CAP_Loss:2.8961 CAP_AVG_Loss:5.1090 Flag_Loss:0.0893 Flag_AVG_Loss:0.0000 CAP_Acc:9.06 Flag_Acc:94.21 Batch_time:0.47s Epoch:0/40 step:800/1065 Loss:0.8386 AVG_Loss:1.6129 CAP_Loss:2.5157 CAP_AVG_Loss:4.8387 Flag_Loss:0.1902 Flag_AVG_Loss:0.0000 CAP_Acc:12.38 Flag_Acc:94.25 Batch_time:0.48s Epoch:0/40 step:900/1065 Loss:0.7938 AVG_Loss:1.5327 CAP_Loss:2.3815 CAP_AVG_Loss:4.5980 Flag_Loss:0.2151 Flag_AVG_Loss:0.0000 CAP_Acc:12.44 Flag_Acc:94.28 Batch_time:0.47s Epoch:0/40 step:1000/1065 Loss:0.7327 AVG_Loss:1.4602 CAP_Loss:2.1982 CAP_AVG_Loss:4.3807 Flag_Loss:0.0488 Flag_AVG_Loss:0.0000 CAP_Acc:12.56 Flag_Acc:94.26 Batch_time:0.46s 12-30 21 : 07 : 35 using real changeflag EVALUATING AT BEAM SIZE 3: 100%|██████████| 6665/6665 [06:13<00:00, 17.85it/s] len(nochange_references): 666 len(change_references): 667 ['Bleu_1', 'Bleu_2', 'Bleu_3', 'Bleu_4'] [0.9999999999992492, 0.9999999999991867, 0.9999999999990823, 0.9999999999988425] Traceback (most recent call last): File "F:/0-code/image-description/PromptCC-main/train.py", line 254, in main(args) File "F:/0-code/image-description/PromptCC-main/train.py", line 196, in main metrics = evaluate(args, test_loader, tokenizer, Caption_model) File "F:\0-code\image-description\PromptCC-main\eval2.py", line 194, in evaluate metrics = get_eval_score(nochange_references, nochange_hypotheses) File "F:\0-code\image-description\PromptCC-main\utils.py", line 188, in get_eval_score score_i, scores_i = scorer.compute_score(ref, hypo) File "F:\0-code\image-description\PromptCC-main\eval_func\meteor\meteor.py", line 41, in compute_score stat = self._stat(res[i][0], gts[i]) File "F:\0-code\image-description\PromptCC-main\eval_func\meteor\meteor.py", line 65, in _stat self.meteor_p.stdin.write(score_line + '\n') OSError: [Errno 22] Invalid argument

或许你可以尝试安装Java1.8（ref: https://github.com/tylin/coco-caption/issues/28

**Comment by X-Wang-99** [comment]
感谢你的回复，我最后使用了ubuntu系统，安装了java1.8，并在meteor目录下放入了meteor-1.5.jar文件。现在已经能够work。
