### ISSUE TITLE
AttributeError: 'GPT2Model' object has no attribute '_attn_implementation' when conducting eval2.py

### ISSUE THREAD

**Issue by Serendi-hi** [Chen-Yang-Liu/PromptCC#9]
我用 BEST_chekpoint_ViT-B_32.pth.tar 作为模型权重运行 eval2.py 或 caption_beams.py 都会报错
(gpt2) ➜  PromptCC-main git:(master) ✗ python caption_beams.py     
11-03  12 : 14 : 01
model_name: ./checkpoints/cap_model/BEST_checkpoint_ViT-B_32.pth.tar
using predicted changeflag
Traceback (most recent call last):
  File "/home/serendi/Desktop/Projects/PromptCC-main/caption_beams.py", line 267, in <module>
    main(args)
  File "/home/serendi/Desktop/Projects/PromptCC-main/caption_beams.py", line 204, in main
    caption = evaluate(args, ori_img, tokenizer, model)
  File "/home/serendi/Desktop/Projects/PromptCC-main/caption_beams.py", line 74, in evaluate
    out = model.gpt_decoder(inputs_embeds=inputs_embeds)
  File "/home/serendi/anaconda3/envs/gpt2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/serendi/anaconda3/envs/gpt2/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1271, in forward
    transformer_outputs = self.transformer(
  File "/home/serendi/anaconda3/envs/gpt2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/serendi/anaconda3/envs/gpt2/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1035, in forward
    _use_sdpa = self._attn_implementation == "sdpa" and output_attentions is False and head_mask is None
  File "/home/serendi/anaconda3/envs/gpt2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPT2Model' object has no attribute '_attn_implementation'

train.py可以正常训练，请求指导，非常感谢！

**Comment by Serendi-hi** [comment]
已解决，是transformer的版本问题，降级到requirements.txt中的版本就可以正常运行了。
